//------------------------------------------------------------------------
// Copyright(c) 2026 lueroth.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"genTest.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"genTest VST3 (64Bit)"
#else
#define stringFileDescription	"genTest VST3"
#endif
#define stringCompanyName		"lueroth\0"
#define stringLegalCopyright	"Copyright(c) 2026 lueroth."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
